name = "broono-api"
main = "src/index.ts"
compatibility_date = "2024-12-18"

[vars]
FRONTEND_URL = "http://localhost:5176"

[[d1_databases]]
binding = "DB"
database_name = "broono-db"
database_id = "16c0b6bd-23d5-46a8-8083-491fedf3eb73"
